services:
  - type: web
    name: mehedi-key-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: ADMIN_TOKEN
        sync: false